[package]
name = "emuiibo"
version = "0.6.3"
authors = ["XorTroll"]
edition = "2018"

[dependencies]
nx = { path = "../../aarch64-switch-rs/nx" }
paste = "1.0"

[dependencies.serde]
version = "1.0"
default-features = false
features = ["derive"]

[dependencies.serde_json]
version = "1.0"
default-features = false
features = ["alloc"]

[package.metadata.sprinkle.nsp]
npdm = "npdm.json"