name: Build emutool

on:
  push:
    paths:
      - 'emutool/**'

jobs:
  emutool:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Build
      run: msbuild emutool/emutool.sln -t:Build -p:Configuration=Release

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: emutool
        path: emutool/emutool/bin/Release